#!/bin/bash
set -e

REPO=$HOME/bitpivot-web.git/
TMP=$HOME/tmp/bitpivot-web.git/
WWW=/www/bitpivot/versions/bitpivot-2.0/

rm -rf $TMP || true
git clone $REPO $TMP
cd $TMP
rake
rsync --recursive --delete _site/. $WWW
cd
rm -rf $TMP