development:
  adapter: postgresql
  encoding: unicode
  database: bitpivot_development
  pool: 5
  timeout: 5000
  host: localhost
  user: rails
  password: rails

test:
  adapter: postgresql
  encoding: unicode
  database: bitpivot_test
  pool: 5
  timeout: 5000
  host: localhost
  user: rails
  password: rails

production:
  adapter: postgresql
  encoding: unicode
  database: bitpivot_production
  pool: 5
  timeout: 5000
  host: localhost
  user: rails
  password: rails
