development:
  adapter: postgresql
  encoding: unicode
  database: bitpivot_development
  host: localhost
  pool: 5
  username: rails
  password: rails

test:
  adapter: postgresql
  encoding: unicode
  database: bitpivot_test
  host: localhost
  pool: 5
  username: rails
  password: rails

production:
  adapter: postgresql
  encoding: unicode
  database: bitpivot_production
  host: localhost
  pool: 5
  username: rails
  password: rails

loadimpact:
  adapter: postgresql
  encoding: unicode
  database: bitpivot_production
  host: localhost
  pool: 5
  username: rails
  password: rails